server:
  port: 6060

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CrowerAuthDB
    username: postgres
    password: asd123asd
  jpa:
    hibernate:
      ddl-auto: update