server:
  port: 9999
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: elastic-search-posts
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  elasticsearch:
    uris: http://localhost:9200